apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: oladayur/registration:v3
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_USERNAME
          value: admin
        - name: MONGO_DB_PASSWORD
          value: admin@123
        - name: MONGO_DB_HOSTNAME
          value: mongo-svc

---

apiVersion: v1
kind: Service
metadata:
  name: todo-svc
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31023

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodb-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongodb
    spec:
      volumes:
        - name: mongo-vol
          hostPath: 
            path: /tmp/mongo
      containers:
        - name: mongodb-con
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
          - name: mongo-vol
            mountPath: /data/db
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: admin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: admin@123

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
